version: '3.4'

services:
  corkedfever.jobs.service:
    image: ${DOCKER_REGISTRY-}corkedfeverjobsservice
    build:
      context: Corkedfever.Jobs.Service
      dockerfile: Dockerfile
    ports:
      -  "26006:8080"
      -  "26007:8081"
